# Generated by Django 4.1 on 2022-09-14 19:21

import base.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to=base.models.upload_to),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='size',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
