# Generated by Django 4.1 on 2022-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Employer'), (2, 'Candidate')], default=1),
        ),
    ]
