# Generated by Django 4.1 on 2022-10-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='jobApplication',
            new_name='job_application',
        ),
    ]
