# Generated by Django 4.1 on 2022-09-19 18:41

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_candidateprofile_website_alter_candidateprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='designation',
            field=models.CharField(blank=True, default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_raw_text',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='about',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to=base.models.upload_to),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='slogan',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='experience',
            name='range',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
