# Generated by Django 4.1 on 2022-09-17 09:34

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_employerprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.FileField(blank=True, default='', upload_to=base.models.upload_to),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
