# Generated by Django 4.1 on 2022-09-01 11:50

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EMPLOYER'), (2, 'CANDIDATE')], default=1),
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=80, null=True)),
                ('org_website', models.CharField(max_length=100, null=True)),
                ('org_description', models.TextField(null=True)),
                ('org_location', models.CharField(max_length=100, null=True)),
                ('org_size', models.CharField(max_length=100, null=True)),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to=base.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
