# Generated by Django 4.1 on 2022-09-17 19:48

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_candidateprofile_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.FileField(blank=True, default='', upload_to=base.models.upload_resume_to),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('CandidateProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidateprofile')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.education')),
                ('experince', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.experience')),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
                ('skills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.skills')),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.social')),
            ],
        ),
    ]
