# Generated by Django 4.1 on 2022-09-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_candidateprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='url',
        ),
        migrations.AlterField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='base.candidateprofile'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('level', models.CharField(blank=True, max_length=80, null=True)),
                ('salary', models.CharField(blank=True, max_length=80, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('benefits', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='base.employerprofile')),
            ],
        ),
    ]
