# Generated by Django 4.1 on 2022-09-18 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_candidateprofile_resume_file_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='skills',
            name='resume_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='base.resume'),
            preserve_default=False,
        ),
    ]
