# Generated by Django 4.1 on 2022-09-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_social_url_alter_experience_candidate_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidateprofile'),
        ),
    ]
