# Generated by Django 4.1 on 2022-09-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_resume_skills_skills_resume_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.candidateprofile')),
            ],
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
