# Generated by Django 4.1 on 2022-11-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact_newsletter_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Community Posts'},
        ),
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'verbose_name_plural': 'Candidate Profiles'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='employerprofile',
            options={'verbose_name_plural': 'Employer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name_plural': 'Interview Invitations'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name_plural': 'Manage Users'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Manage Vacancies'},
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=True, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EMPLOYER'), (2, 'CANDIDATE'), (69, 'ADMIN')], default=1),
        ),
    ]
