# Generated by Django 4.1 on 2022-09-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_skill_rename_projects_project_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='base.candidateprofile'),
        ),
    ]
