# Generated by Django 4.1 on 2022-10-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='JobApplication',
        ),
    ]
