# Generated by Django 4.1 on 2022-10-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_application_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='nlp_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skill_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
