# Generated by Django 4.1 on 2022-10-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_invitation_delete_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='designation',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='size',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='slogan',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='range',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='benefits',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='qualifications',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
