# Generated by Django 4.1 on 2022-10-15 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_candidateprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='invitation',
            name='job_application',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='base.jobapplication'),
            preserve_default=False,
        ),
    ]
